name: Seunghwa Rho
markdown: kramdown
title: Seunghwa Rho Economics
description: Seunghwa Rho Personal Webpage (Econometrics Economics QTM Emory)
url: http://seunghwaRho.github.io
plugins: 
  - jekyll-sitemap
  - jekyll-seo-tag
google_analytics: UA-141513535-1

theme: jekyll-theme-minimal