name: Seunghwa Rho
markdown: kramdown
title: Seunghwa Rho 
description: Seunghwa Rho - personal webpage
url: http://seunghwaRho.github.io
plugins: 
  - jekyll-sitemap
  - jekyll-seo-tag
google_analytics: UA-141513535-1

theme: jekyll-theme-minimal